### ISSUE TITLE
IMC

### ISSUE THREAD

**Issue by Danyllo-Mendanha-dev** [Danyllo-Mendanha-dev/Projects-HTML-CSS-JS#1]
```js
const calcular = document.getElementById('calcular')

const returnClassification = valueIMC => {
  let classification = ''

    classification = valueIMC < 18.5 ? 'abaixo do peso' :
    valueIMC < 25 ? 'com peso normal' :
    valueIMC < 30 ? 'com sobrepeso':
    valueIMC < 35 ? 'com obesidade grau I':
    valueIMC < 40 ? 'com obesidade grau II':
      'com obesidade grau III'
  
  return classification
}

const handleMessageImc = (name, heigth, weight, result) => {
  const spaceIsFilled = name !== '' && heigth !== '' && weight !== ''

  if (spaceIsFilled){
    
    const valueIMC = (weight / (heigth * heigth)).toFixed(1)
    const classification = returnClassification(valueIMC)

    result.textContent = `${name} seu IMC é ${valueIMC} e você está ${classification}`

  } else {
    result.textContent = 'Obs: Preencha todos os campos'
  }
}

const imc = () => {
  const name = document.getElementById('nome').value
  const heigth = document.getElementById('altura').value
  const weight = document.getElementById('peso').value
  const result = document.getElementById('resultado')

  handleMessageImc(name, heigth, weight, result)
}

calcular.addEventListener('click', imc)
```

```html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IMC</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <main>
      <div class="container">
        <div class="title"> Calculadora - IMC </div>
        <div class="input">
            <label>Nome:</label>
            <input type="text" id='nome'>
        </div>
        <div class="input">
            <label>Altura:</label>
            <input type="number" id='altura' min=0>
        </div>
        <div class="input">
            <label>Peso:</label>
            <input type="number" id='peso' min=0>
        </div>
        <button id='calcular'>Calcular</button>

        <div class="result" id='resultado'></div>
      </div>
    </main>
    <script src="./imc.js"></script>
  </body>
</html>
```

```css
main{
  display: flex;
  width: 100vw;
  height: 100vh;
  justify-content: center;
  align-items: center;

}

.container{
  display: flex;
  flex-direction: column;
  background: rgb(255,198,0);
  width: 400px;
  height: 600px;
  align-items: center;
  justify-content: space-evenly;
  border-radius: 20px;
  box-shadow: 0 0 10px black;
}

.title{
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 50px;
  font: bold 2.5rem serif;
  border-bottom: solid 5px black;
  margin-bottom: 20px;
}

.input {
  display: flex;
  width: 300px;
  height: 50px;
  justify-content: space-between;
  align-items: center;
}
.input input {
  width: 200px;
  height: 50px;
  border-radius: 5px;
  border:none;
  outline: 0;
  font: bold 1.5rem serif;
  text-align: center;
}

.input label {
  font: bold 1.5rem serif;
}

button{
  width: 300px;
  height: 40px;
  font: bold 1.2rem serif;
  background: #000;
  color: rgb(255,198,0);
  outline: none;
  border-radius: 5px;
  cursor: pointer;
}

.result{
  display: flex;
  margin-top: 20px;
  align-items: center;
  width: 300px;
  height: 150px;
  border-radius: 5px;
  font: italic 1.5rem serif;
  box-shadow: 0px 0px 10px black;
  background: #000;
  color: rgb(255,198,0);
  padding: 20px;
  box-sizing: border-box;
  user-select: none;
}
```
