### ISSUE TITLE
DrumKit

### ISSUE THREAD

**Issue by Danyllo-Mendanha-dev** [Danyllo-Mendanha-dev/Projects-HTML-CSS-JS#5]
```js
'use strict'

const sons = {
  'A': 'boom.wav',
  'S': 'clap.wav',
  'D': 'hihat.wav',
  'F': 'kick.wav',
  'G': 'openhat.wav',
  'H': 'ride.wav',
  'J': 'snare.wav',
  'K': 'tink.wav',
  'L': 'tom.wav',
}

const container = document.getElementById('container')

const createDiv = text => {
    const div = document.createElement('div')
    div.classList.add('key')
    div.textContent = text
    div.id = text
    container.appendChild(div)
}

const show = sons => Object.keys(sons).forEach(createDiv)

const playSound = letter => {
  const audio = new Audio(`./sounds/${sons[letter]}`)
  audio.play()
}

const addEffect = letter => 
    document.getElementById(letter).classList.toggle('active')  

const removeEffect = letter => {
  const div = document.getElementById(letter)
  const removeActive = () => div.classList.remove('active')
  div.addEventListener('transitionend', removeActive)
}

const activateDiv = event => {
  const letter = event.type === 'click' ? event.target.id : event.key.toUpperCase()

  const permittedLetter = sons.hasOwnProperty(letter)

  if (permittedLetter) {
    addEffect(letter)
    playSound(letter)
    removeEffect(letter)
  }
}

show(sons)
container.addEventListener('click', activateDiv)

window.addEventListener('keyup', activateDiv)
```

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="style.css">
  <title>DRUM KIT</title>
</head>
<body>
    <main>
      <div class="title">DRUM KIT</div>
      <div class="container" id="container"></div>
      <script src="./app.js"></script>
    </main>
</body>
</html>
```

```css
*{
  margin: 0;
  padding:0;
  box-sizing: border-box;
}

body{
  background-image: url('./img/back.jpg');
  background-size: cover;
  width: 100vw;
  height: 100vh;
  font-family: 'Open Sans', sans-serif;
}

main{
  display: flex;
  flex-direction: column;
}

.title{
  color: #ffcc00;
  margin: 20vh auto;
  font-size: calc(5vw + 20px);
  text-shadow: 0 0 10px black,
               0 0 10px black,
               0 0 10px black;
}

.container{
  width: 90vw;
  height: 100px;
  margin: 0 auto;
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: space-around;
  gap: 15px;
}
.key{
  display: flex;
  width: 100px;
  height: 100px;
  align-items: center;
  justify-content: center;
  background-color: #000000BB;
  color: white;
  font-size: calc(3vw + 20px);
  border: 3px solid white;
  user-select: none;
  cursor: pointer;
  transition: transform .2s;
}

.active{
  transform: scale(1.3);
  border-color: #ffcc00;
  box-shadow: 0 0 50px #ffcc00;
}
```
![back](https://github.com/Danyllo-Mendanha-dev/Projects/assets/129876716/770a9d12-df20-4ff4-b4e9-31a223c0152e)
