### ISSUE TITLE
Calculadora

### ISSUE THREAD

**Issue by Danyllo-Mendanha-dev** [Danyllo-Mendanha-dev/Projects-HTML-CSS-JS#6]
```js
'use strict'

const display = document.getElementById('display')
const numbers = document.querySelectorAll('[id*=tecla')
const operators = document.querySelectorAll('[id*=operador]')

let newNumber = true
let operator
let previousNumber

const operationPending = () => operator !== undefined

const calculate = () => {
  if (operationPending()) {
    const currentNumber = display.textContent.replace('.', '').replace(',', '.')
    newNumber = true
    const result = eval(`${previousNumber}${operator}${currentNumber}`)
    updateDisplay(result)
  }
}

const updateDisplay = text => {
  if (newNumber) {
    display.textContent = text.toLocaleString('BR')
    newNumber = false
  } else {
    display.textContent += text.toLocaleString('BR')
  }
  document.querySelector('#igual').focus()
}

const insertNumber = event => updateDisplay(event.target.textContent)
numbers.forEach(number => number.addEventListener('click', insertNumber))

const selectOperator = event => {
  if (!newNumber) {
    calculate()
    newNumber = true
    operator = event.target.textContent
    previousNumber = parseFloat(display.textContent.replace('.', '').replace(',', '.'))
  }
}

operators.forEach(operator => operator.addEventListener('click', selectOperator))

const activateEqual = () => {
  calculate()
  operator = undefined
}
document.getElementById('igual').addEventListener('click', activateEqual)

const clearDisplay = () => (display.textContent = '')
document.getElementById('limparDisplay').addEventListener('click', clearDisplay)

const clearCalculate = () => {
  clearDisplay()
  operator = undefined
  newNumber = true
  previousNumber = undefined
}
document.getElementById('limparCalculo').addEventListener('click', clearCalculate)

const removeLastNumber = () => (display.textContent = display.textContent.slice(0, -1))
document.getElementById('backspace').addEventListener('click', removeLastNumber)

const reverseSignal = () => {
  newNumber = true
  updateDisplay(display.textContent * -1)
}
document.getElementById('inverter').addEventListener('click', reverseSignal)

const existDecimal = () => display.textContent.indexOf(',') !== -1
const existValue = () => display.textContent.length > 0
const insertDecimal = () => {
  if (!existDecimal()) {
    if (newNumber) {
      updateDisplay('0,')
    } else {
      updateDisplay(',')
    }
  }
}
document.getElementById('decimal').addEventListener('click', insertDecimal)

const mapaTeclado = {
  0: 'tecla0',
  1: 'tecla1',
  2: 'tecla2',
  3: 'tecla3',
  4: 'tecla4',
  5: 'tecla5',
  6: 'tecla6',
  7: 'tecla7',
  8: 'tecla8',
  9: 'tecla9',
  '/': 'operadorDividir',
  '*': 'operadorMultiplicar',
  '-': 'operadorSubtrair',
  '+': 'operadorAdicionar',
  '=': 'igual',
  Enter: 'igual',
  Backspace: 'backspace',
  c: 'limparDisplay',
  Escape: 'limparCalculo',
  ',': 'decimal',
}

const mapKeyboard = event => {
  const keyboard = event
  const permitedKey = () => Object.keys(mapaTeclado).indexOf(keyboard) !== -1
  if (permitedKey()) document.getElementById(mapaTeclado[keyboard]).click()
}
document.addEventListener('keydown', mapKeyboard)
```

```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>calculadora</title>
</head>
<body>
    <div class="calculator">
        <div class="display" id="display"></div>
        <div class="calculator-buttons">
            <button id="limparDisplay">CE</button>
            <button id="limparCalculo">C</button>
            <button id="backspace">«</button>
            <button id="operadorDividir">/</button>
            <button id="tecla7">7</button>
            <button id="tecla8">8</button>
            <button id="tecla9">9</button>
            <button id="operadorMultiplicar">*</button>
            <button id="tecla4">4</button>
            <button id="tecla5">5</button>
            <button id="tecla6">6</button>
            <button id="operadorSubtrair">-</button>
            <button id="tecla1">1</button>
            <button id="tecla2">2</button>
            <button id="tecla3">3</button>
            <button id="operadorAdicionar">+</button>
            <button id="inverter">±</button>
            <button id="tecla0">0</button>
            <button id="decimal">,</button>
            <button id="igual">=</button>
        </div>
    </div>
    <script src="calculadora.js"></script>
</body>
</html>
```

```css
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body{
  background-color: whitesmoke;
  padding: 90px 0;
}

.calculator {
  width: 400px;
  margin: 0 auto;
  background-color: #FBAB18;
  padding: 20px;
  border-radius: 5px;
  box-shadow: 0 0 15px black;
}

.display{
  display: flex;
  justify-content: flex-end;
  width: 100%;
  height: 100px;
  margin-bottom: 20px;
  padding: 15px;
  background-color: black;
  color: white;
  font: normal 4rem serif;
  overflow: hidden;
  border-radius: 5px;
}

.calculator-buttons{
  display: grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  grid-gap: 10px;
}

.calculator button{
  background-color: black;
  color: white;
  padding: 20px;
  border-radius: 5px;
  font-size: 1.5rem;
  outline: none;
  cursor: pointer;
  border: 2px solid black;
}

button:hover{
  background-color: #FBAB18;
  color: black;
}
```
