### ISSUE TITLE
CountDown

### ISSUE THREAD

**Issue by Danyllo-Mendanha-dev** [Danyllo-Mendanha-dev/Projects-HTML-CSS-JS#7]
```js
'use strict';

const formatarDigito = (digito) => `0${digito}`.slice(-2)


const calcularSegundos = tempo => {
    return tempo % 60
}

const calcularMinutos = tempo => {
    return Math.floor((tempo % (60 * 60)) / 60)
}

const calcularHoras = tempo => {
    return Math.floor((tempo % (60 * 60 * 24)) / (60 * 60))
}

const calcularDias = tempo => {
    return Math.floor(tempo / (60 * 60 * 24))
}

const calcularTempo = tempo => {
    const qtdSegundos = calcularSegundos(tempo)
    const qtdMinutos = calcularMinutos(tempo)
    const qtdHoras = calcularHoras(tempo)
    const qtdDias = calcularDias(tempo)

    return {qtdSegundos, qtdMinutos, qtdHoras, qtdDias}
}

const atualizar = tempo => {
    const segundos = document.getElementById('segundos')
    const minutos = document.getElementById('minutos')
    const horas = document.getElementById('horas')
    const dias = document.getElementById('dias')

    const {qtdSegundos, qtdMinutos, qtdHoras, qtdDias} = calcularTempo(tempo)

    segundos.textContent = formatarDigito(qtdSegundos)
    minutos.textContent = formatarDigito(qtdMinutos)
    horas.textContent = formatarDigito(qtdHoras)
    dias.textContent = formatarDigito(qtdDias)
}

const contagemRegressiva = tempo => {
    const pararContagem = () => clearInterval(id)

    const contar = () => {
        if (tempo === 0 ){
            pararContagem()
        }
        atualizar(tempo)
        tempo--
    }
    const id = setInterval(contar,1000)
}

const tempoRestante = () => {
    // 1 de janeiro de 1970
    const dataEvento = new Date ('2020-10-26 20:00:00')
    const hoje = Date.now()
    return Math.floor((dataEvento - hoje) / 1000)
}

contagemRegressiva(tempoRestante())
```
```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Count Down</title>
  <link rel="stylesheet" href="style.css">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
</head>
<body>
  
  <div class="container">
    <div class='title'>
        <h1>LIVE</h1>
        <p>Em breve</p>
    </div>

    <div class="countdown">
        <div >
            <h1 id="dias">00</h1>
            <p>Dias</p>
        </div>
        <div>
            <h1 id="horas">00</h1>
            <p>Horas</p>
        </div>
        <div>
            <h1  id="minutos">00</h1>
            <p>Minutos</p>
        </div>
        <div>
            <h1 id="segundos">00</h1>
            <p>Segundos</p>
        </div>
    </div>

    <div class='button'>
        <p>Cadastre-se</p>
    </div>
</div>

  <script src="app.js"></script>
</body>
</html>
```

```css
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body{
  background-image: url('./bg/bg.jpg');
  color: whitesmoke;
  font-family: 'Montserrat', sans-serif;
  user-select: none;
}

.container{
  display: flex;
  flex-direction: column;
  width: 100vw;
  height: 100vh;
  align-items: center;
  justify-content: space-evenly;
  text-align: center;
  background-color: #00000080;
}

.title{
  font-size: calc(10px + 3vw);
}

.title p{
  font-size: calc(10px + 1vw);
}

.countdown{
  display: flex;
  width: 60vw;
  justify-content: space-between;
  flex-wrap: wrap;
}

.countdown h1{
  font-size: calc(10px + 8vw);
  text-shadow: 0 0 10px whitesmoke;
}

.button{
  background-color: whitesmoke;
  color: black;
  padding: 10px;
  cursor: pointer;
  border: solid 2px whitesmoke;
}

.button:hover{
  background-color: black;
  color: whitesmoke;
}
```
![bg](https://github.com/Danyllo-Mendanha-dev/Projects/assets/129876716/3aa46c8b-6edd-4d5b-801d-9c0bc71e25c2)
