### ISSUE TITLE
Todo-List

### ISSUE THREAD

**Issue by Danyllo-Mendanha-dev** [Danyllo-Mendanha-dev/Projects-HTML-CSS-JS#8]
```js
'use strict'

let bank = [
    {'tarefa': 'ESTUDAR BD', 'status': ''},
    {'tarefa': 'ESTUDAR LP', 'status': ''}
]

const getBank = () => JSON.parse(localStorage.getItem('todoList')) ?? []
const setBank = bank => localStorage.setItem('todoList', JSON.stringify(bank))


const createItem = (task, status, index) => {
    const item = document.createElement('label')
    item.classList.add('todo__item')
    item.innerHTML = `
    <input type="checkbox" ${status} data-indice="${index}">
    <div>${task}</div>
    <input type="button" value="X" data-indice="${index}">
    `
    document.getElementById('todoList').appendChild(item)
}

const clearTask = () => {
    const todoList = document.getElementById('todoList')
    while(todoList.firstChild) {
        todoList.lastChild.remove()
    }
}

const updateScreen = () => {
    clearTask()
    const bank = getBank()
    bank.forEach((item, index) => createItem(item.tarefa, item.status, index))
    setBank(bank)
}

const insertItem = event => {
    const key = event.key
    const text = event.target.value
    if (key === 'Enter') {
        const bank = getBank()
        bank.push({'tarefa': text, 'status': ''})
        setBank(bank)
        updateScreen()
        event.target.value = ''
    }
}

const removeItem = index => {
    const bank = getBank()
    bank.splice(index, 1)
    setBank(bank)
    updateScreen()
}

const updateItem = index => {
    const bank = getBank()
    bank[index].status = bank[index].status === '' ? 'checked' : ''
    setBank(bank)
    updateScreen()
}

const clickItem = event => {
    const element = event.target
    if (element.type === 'button') {
        const index = element.dataset.indice
        removeItem(index)
    } else if(element.type === 'checkbox') {
        const index = element.dataset.indice
        updateItem(index)
    }
}

document.getElementById('newItem').addEventListener('keypress', insertItem)
document.getElementById('todoList').addEventListener('click', clickItem)

updateScreen()
```
```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>todo-list</title>
</head>
<body>
    <div class="todo">
        <div class="todo__title">
            TODO - LIST
        </div>

        <div class="todo__list" id='todoList'>

        </div>

        <div class="todo__new-item" id="newItem">
            <div>&and;</div>
            <input type="text" placeholder="Digite e pressione enter para adicionar a tarefa">
            <div>&and;</div>
        </div>
    </div>
    <script src="app.js"></script>
</body>
</html>
```

```css
:root {
  --primary-color: #F4CE01;
  --secondary-color: #0F0F0B;
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}
html {
  font-size: 62.5%;
}

body {
  background-color: var(--primary-color);
  font: bold 2rem 'Open Sans', sans-serif;
}

.todo {
  display: flex;
  width: 50vw;
  flex-direction: column;
  align-items: center;
  margin: 0 auto;
  gap: 15px;
}

.todo__title {
  display: flex;
  background-color: var(--secondary-color);
  width: 100%;
  height: 80px;
  justify-content: center;
  align-items: center;
  margin-top: 50px;
  box-shadow: 1px 1px 5px var(--secondary-color);
  font-size: 3rem;
  color: var(--primary-color);
}

.todo__list {
  display: flex;
  width: 100%;
  flex-direction: column;
  gap: 10px;
}

.todo__item{
  display: flex;
  width: 100%;
  height: 60px;
  justify-content: space-between;
  align-items: center;
  padding: 5px;
  box-shadow: 1px 1px 5px var(--secondary-color);
}
.todo__item > div {
  width: 80%;
}
.todo__item:hover {
  cursor: pointer;
  transition: all .5s ease;
  background-color: var(--secondary-color);
  color: var(--primary-color);
}


.todo__item > input[type='text'] {
  border: none;
  width: 80%;
  font: inherit;
}

.todo__item > input[type='button'],
.todo__item > input[type='checkbox'] {
  width: 30px;
  height: 30px;
  font: inherit;
}


.todo__item > input[type='checkbox']:checked  + div {
  text-decoration: line-through;
}

.todo__new-item{
  display: flex;
  background-color: #fff59d;
  width: 100%;
  height: 70px;
  justify-content: space-evenly;
  padding: 10px 0;
  box-shadow: 1px 1px 5px var(--secondary-color);
  margin: 10px;
  font: inherit;
}

.todo__new-item > input{
  background-color: #fff59d;
  border: none;
  width: 80%;
  outline: none;
  font: inherit;
}

.todo__new-item > input::placeholder {
  font-style: italic;
  font-weight: normal;
}
```
